import Vue from 'vue'
import Vuex from 'vuex'
Vue.use(Vuex)

export default new Vuex.Store({
    state:{
        leaderboard:{
            id:'',
            userid:'',
            placement:'',
            platform:'',
            value:'',
        },
        playerDetail:[],
        content:{
            data:{
                playerId:'',
                platform:'',
                name:'',
                level:'',
                stats:{
                    bomb:{
                        bestScore:0,
                        lost:0,
                        played:0,
                        won:0
                        },
                        casual:{
                        deaths:0,
                        kills:0,
                        lost:0,
                        played:0,
                        timePlayed:0,
                        won:0
                        },
                        custom:{
                        timePlayed:0
                        },
                        general:{
                        assists:0,
                        blindKills:0,
                        bulletsFired:0,
                        bulletsHit:0,
                        dbno:0,
                        dbnoAssists:0,
                        deaths:0,
                        gadgetsDestroyed:0,
                        headshot:0,
                        hostageDefense:0,
                        hostageRescue:0,
                        kills:0,
                        lost:0,
                        meleeKills:0,
                        penetrationKills:0,
                        played:0,
                        rappelBreaches:0,
                        revives:0,
                        revivesDenied:0,
                        serverAggression:0,
                        serverDefender:0,
                        serversHacked:0,
                        suicides:0,
                        timePlayed:0,
                        won:0
                        },
                        hostage:{
                        bestScore:0,
                        lost:0,
                        played:0,
                        won:0
                        },
                        secure:{
                            bestScore:0,
                            lost:0,
                            played:0,
                            won:0
                            }
                },
                lastPlayed:{
                    ranked:'/',
                    causual:'/',
                },
                progressions:{
                    stats:{
                        casual:{
                            kills:'',
                            deaths:'',
                        }
                    }
                },
                
                rank:{
                    apac:{}
                }
            },
        },
    },
    mutations:{
        initData(state){
            state.playerDetail=[],
            
            state.content={
                
                data:{
                    playerId:'',
                    platform:'',
                    name:'',
                    level:'/',
                    stats:{
                        bomb:{
                            bestScore:0,
                            lost:0,
                            played:0,
                            won:0
                            },
                            casual:{
                            deaths:0,
                            kills:0,
                            lost:0,
                            played:0,
                            timePlayed:0,
                            won:0
                            },
                            custom:{
                            timePlayed:0
                            },
                            general:{
                            assists:0,
                            blindKills:0,
                            bulletsFired:0,
                            bulletsHit:0,
                            dbno:0,
                            dbnoAssists:0,
                            deaths:0,
                            gadgetsDestroyed:0,
                            headshot:0,
                            hostageDefense:0,
                            hostageRescue:0,
                            kills:0,
                            lost:0,
                            meleeKills:0,
                            penetrationKills:0,
                            played:0,
                            rappelBreaches:0,
                            revives:0,
                            revivesDenied:0,
                            serverAggression:0,
                            serverDefender:0,
                            serversHacked:0,
                            suicides:0,
                            timePlayed:0,
                            won:0
                            },
                            hostage:{
                            bestScore:0,
                            lost:0,
                            played:0,
                            won:0
                            },
                            secure:{
                                bestScore:0,
                                lost:0,
                                played:0,
                                won:0
                                }
                    },
                    lastPlayed:{
                        ranked:'/',
                        causual:'/',
                    },
                    
                    rank:{
                        apac:{}
                    }
                },
            }
        }
    },
    actions:{
        initData({commit}){
            commit('initData')
            }
        },
    getters:{
        },


})